version: "3.8"

services:
  backend:
    build:
      context: ./nestBackEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./quokka-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
